//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPedidosNotificacao.UI.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Entidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entidade()
        {
            this.Pedidos = new HashSet<Pedido>();
        }

        public int Id { get; set; }

        [Display(Name = "Designação")]
        public string Denoninacao { get; set; }

        [Display(Name = "Nº Processo")]
        public string NumeroProcesso { get; set; }

        [Display(Name = "Tipo")]
        public Nullable<int> EntidadeTipoId { get; set; }

        [Display(Name = "Data de Cadastro")]
        public Nullable<System.DateTime> DataEntidade { get; set; }

        public virtual EntidadeTipo EntidadeTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}
