//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPedidosNotificacao.UI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosHistorico
    {
        public int Id { get; set; }
        public int PedidoId { get; set; }
        public Nullable<int> UtilizadorId { get; set; }
        public string EstadoId { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> DataFactura { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
