//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPedidosNotificacao.UI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidosHistoricoes = new HashSet<PedidosHistorico>();
        }
    
        public int Id { get; set; }
        public string Finalidade { get; set; }
        public Nullable<int> EntidadeId { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> DataFactura { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public Nullable<int> UtilizadorId { get; set; }
        public Nullable<int> ServicoId { get; set; }
        public string NumProcesso { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosHistorico> PedidosHistoricoes { get; set; }
        public virtual ServicoProduto ServicoProduto { get; set; }
        public virtual Entidade Entidade { get; set; }
    }
}
